[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/state"
  to = "/.netlify/functions/state"
  status = 200

[[redirects]]
  from = "/api/deputados"
  to = "/.netlify/functions/deputados"
  status = 200
